services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile # Dockerfile.dev for development
    container_name: carter_client
    # env_file:              #vite env's are static by nature (embedded during build  time)
    #   - ./client/.env
    ports:
      - "3000:3000"
    # volumes:                  #uncomment for development
    #   - ./client:/app/client
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: carter_server
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    # volumes:                    #uncomment for development
    #   - ./server:/app/server
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: code
    container_name: carter_DB
    volumes:
      - carterDB_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: carter_redis
    ports:
      - "6379:6379"

volumes:
  carterDB_data:
